import datetime
from gemini_instruments.common import Section

fixture_data = {
    ('GHOST', 'sky95_std_MEF_2x2_slit.fits'): (('airmass', 5.119036129013121),
                                               ('amp_read_area',
                                                ["'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]"]),
                                               ('ao_seeing', None),
                                               ('arm', 'slit'),
                                               ('array_name',
                                                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
                                               ('array_section',
                                                [Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885)]),
                                               ('azimuth', 189.2873890821772),
                                               ('calibration_key', (
                                               'GS-2016B-Q-20-6-001', 'slit')),
                                               ('camera', 'Slit'),
                                               ('cass_rotator_pa',
                                                -187.344883172036),
                                               ('central_wavelength', None),
                                               ('coadds', 1),
                                               ('data_label',
                                                'GS-2016B-Q-20-6-001'),
                                               ('data_section',
                                                [Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160)]),
                                               ('dec', None),
                                               ('decker', None),
                                               ('detector_name', 'Sony-ICX674'),
                                               (
                                               'detector_roi_setting', 'Fixed'),
                                               (
                                               'detector_rois_requested', None),
                                               ('detector_section',
                                                [Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885)]),
                                               ('detector_x_bin', 2),
                                               ('detector_x_offset', None),
                                               ('detector_y_bin', 2),
                                               ('detector_y_offset', None),
                                               ('disperser', None),
                                               ('dispersion', None),
                                               ('dispersion_axis', None),
                                               ('effective_wavelength', None),
                                               ('elevation', 11.29267010175693),
                                               ('exposure_time', None),
                                               ('filter_name', None),
                                               ('focal_plane_mask', None),
                                               ('gain',
                                                [1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                                                 1.0, 1.0, 1.0, 1.0]),
                                               ('gain_setting', None),
                                               ('gcal_lamp', None),
                                               ('group_id',
                                                'GS-2016B-Q-20-6_std_slit_2_2_std'),
                                               ('instrument', 'GHOST'),
                                               ('is_ao', False),
                                               ('is_coadds_summed', True),
                                               ('local_time',
                                                datetime.time(10, 11, 5)),
                                               ('lyot_stop', None),
                                               ('mdf_row_id', None),
                                               (
                                               'nominal_atmospheric_extinction',
                                               0.0),
                                               ('nominal_photometric_zeropoint',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('non_linear_level',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('object', ''),
                                               ('observation_class', ''),
                                               ('observation_epoch', None),
                                               ('observation_id',
                                                'GS-2016B-Q-20-6'),
                                               ('observation_type', 'SKY'),
                                               ('overscan_section',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('pixel_scale', None),
                                               ('program_id', 'GS-2016B-Q-20'),
                                               ('pupil_mask', None),
                                               ('qa_state', 'Pass'),
                                               ('ra', None),
                                               ('raw_bg', None),
                                               ('raw_cc', None),
                                               ('raw_iq', None),
                                               ('raw_wv', None),
                                               ('read_mode', None),
                                               ('read_noise',
                                                [8.0, 8.0, 8.0, 8.0, 8.0, 8.0,
                                                 8.0, 8.0, 8.0, 8.0]),
                                               ('read_speed_setting', None),
                                               ('requested_bg', None),
                                               ('requested_cc', None),
                                               ('requested_iq', None),
                                               ('requested_wv', None),
                                               ('res_mode', 'std'),
                                               ('saturation_level',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('slit', None),
                                               ('target_dec', -69.1009167),
                                               ('target_ra', 149.24425),
                                               ('telescope', 'Gemini-South'),
                                               ('telescope_x_offset', None),
                                               ('telescope_y_offset', None),
                                               ('ut_date',
                                                datetime.date(2017, 12, 1)),
                                               ('ut_datetime',
                                                datetime.datetime(2017, 12, 1,
                                                                  23, 11, 5)),
                                               ('ut_time',
                                                datetime.time(23, 11, 5)),
                                               ('want_before_arc', None),
                                               ('wavefront_sensor', None),
                                               ('wavelength_band', None),
                                               ('wcs_dec', None),
                                               ('wcs_ra', None),
                                               ('well_depth_setting', None))
}
