import datetime
from gemini_instruments.common import Section

fixture_data = {
    ('GHOST', 'sky95_std_MEF_2x2_slit.fits'): (('airmass', 5.119036129013121),
                                               ('amp_read_area',
                                                ["'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]",
                                                 "'0':[804:1123,566:885]"]),
                                               ('ao_seeing', None),
                                               ('arm', 'slitv'),
                                               ('array_name',
                                                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
                                               ('array_section',
                                                [Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885)]),
                                               ('azimuth', 189.2873890821772),
                                               ('calibration_key', (
                                                   'GS-2016B-Q-20-6-001',
                                                   'slitv')),
                                               ('camera', 'Slit'),
                                               ('cass_rotator_pa',
                                                -187.344883172036),
                                               ('central_wavelength', None),
                                               ('coadds', 1),
                                               ('data_label',
                                                'GS-2016B-Q-20-6-001'),
                                               ('data_section',
                                                [Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160),
                                                 Section(x1=0, x2=160, y1=0,
                                                         y2=160)]),
                                               ('dec', -69.1009167),
                                               ('decker', None),
                                               ('detector_name', 'Sony-ICX674'),
                                               (
                                                   'detector_roi_setting',
                                                   'Fixed'),
                                               (
                                                   'detector_rois_requested',
                                                   None),
                                               ('detector_section',
                                                [Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885),
                                                 Section(x1=803, x2=1123,
                                                         y1=565, y2=885)]),
                                               ('detector_x_bin', 2),
                                               ('detector_x_offset', None),
                                               ('detector_y_bin', 2),
                                               ('detector_y_offset', None),
                                               ('disperser', None),
                                               ('dispersion', None),
                                               ('dispersion_axis', None),
                                               ('effective_wavelength', None),
                                               ('elevation', 11.29267010175693),
                                               ('exposure_time', 10.0),
                                               ('filter_name', None),
                                               ('focal_plane_mask', None),
                                               ('gain',
                                                [1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                                                 1.0, 1.0, 1.0, 1.0]),
                                               ('gain_setting', None),
                                               ('gcal_lamp', None),
                                               ('group_id',
                                                'GS-2016B-Q-20-6_std_slitv_2_2_std'),
                                               ('instrument', 'GHOST'),
                                               ('is_ao', False),
                                               ('is_coadds_summed', True),
                                               ('local_time',
                                                datetime.time(10, 11, 5)),
                                               ('lyot_stop', None),
                                               ('mdf_row_id', None),
                                               (
                                                   'nominal_atmospheric_extinction',
                                                   0.0),
                                               ('nominal_photometric_zeropoint',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('non_linear_level',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('object', ''),
                                               ('observation_class', ''),
                                               ('observation_epoch', None),
                                               ('observation_id',
                                                'GS-2016B-Q-20-6'),
                                               ('observation_type', 'SKY'),
                                               ('overscan_section',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('pixel_scale', None),
                                               ('program_id', 'GS-2016B-Q-20'),
                                               ('pupil_mask', None),
                                               ('qa_state', 'Pass'),
                                               ('ra', 149.24425),
                                               ('raw_bg', None),
                                               ('raw_cc', None),
                                               ('raw_iq', None),
                                               ('raw_wv', None),
                                               ('read_mode', None),
                                               ('read_noise',
                                                [8.0, 8.0, 8.0, 8.0, 8.0, 8.0,
                                                 8.0, 8.0, 8.0, 8.0]),
                                               ('read_speed_setting', None),
                                               ('requested_bg', None),
                                               ('requested_cc', None),
                                               ('requested_iq', None),
                                               ('requested_wv', None),
                                               ('res_mode', 'std'),
                                               ('saturation_level',
                                                [None, None, None, None, None,
                                                 None, None, None, None, None]),
                                               ('slit', None),
                                               ('target_dec', -69.1009167),
                                               ('target_ra', 149.24425),
                                               ('telescope', 'Gemini-South'),
                                               ('telescope_x_offset', None),
                                               ('telescope_y_offset', None),
                                               ('ut_date',
                                                datetime.date(2017, 12, 1)),
                                               ('ut_datetime',
                                                datetime.datetime(2017, 12, 1,
                                                                  23, 11, 5)),
                                               ('ut_time',
                                                datetime.time(23, 11, 5)),
                                               ('want_before_arc', None),
                                               ('wavefront_sensor', None),
                                               ('wavelength_band', None),
                                               ('wcs_dec', None),
                                               ('wcs_ra', None),
                                               ('well_depth_setting', None)),
    ('GHOST', 'dark95_1_MEF.fits'): (('airmass', 4.944273057424125),
                                     ('amp_read_area',
                                      ["'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'0':[804:1123,566:885]",
                                       "'A':[1:3072,1:3080]",
                                       "'B':[3073:6144,1:3080]",
                                       "'C':[1:3072,3081:6160]",
                                       "'D':[3073:6144,3081:6160]",
                                       "'A':[1:2048,1:2056]",
                                       "'B':[2049:4096,1:2056]",
                                       "'C':[1:2048,2057:4112]",
                                       "'D':[2049:4096,2057:4112]"]),
                                     ('ao_seeing', None),
                                     ('arm', None),
                                     ('array_name',
                                      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'A', 'B',
                                       'C',
                                       'D', 'A', 'B', 'C', 'D']),
                                     ('array_section',
                                      [Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=0, x2=3072, y1=0, y2=3080),
                                       Section(x1=3072, x2=6144, y1=0, y2=3080),
                                       Section(x1=0, x2=3072, y1=3080, y2=6160),
                                       Section(x1=3072, x2=6144, y1=3080,
                                               y2=6160),
                                       Section(x1=0, x2=2048, y1=0, y2=2056),
                                       Section(x1=2048, x2=4096, y1=0, y2=2056),
                                       Section(x1=0, x2=2048, y1=2056, y2=4112),
                                       Section(x1=2048, x2=4096, y1=2056,
                                               y2=4112)]),
                                     ('azimuth', 190.2057130774296),
                                     ('calibration_key',
                                      ('GS-2016B-Q-20-5-001', None)),
                                     ('camera', None),
                                     ('cass_rotator_pa', -187.344883172036),
                                     ('central_wavelength', None),
                                     ('coadds', 1),
                                     ('data_label', 'GS-2016B-Q-20-5-001'),
                                     ('data_section',
                                      [Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=160, y1=0, y2=160),
                                       Section(x1=0, x2=3072, y1=0, y2=3080),
                                       Section(x1=0, x2=3072, y1=0, y2=3080),
                                       Section(x1=0, x2=3072, y1=0, y2=3080),
                                       Section(x1=0, x2=3072, y1=0, y2=3080),
                                       Section(x1=0, x2=2048, y1=0, y2=2056),
                                       Section(x1=0, x2=2048, y1=0, y2=2056),
                                       Section(x1=0, x2=2048, y1=0, y2=2056),
                                       Section(x1=0, x2=2048, y1=0, y2=2056)]),
                                     ('dec', -69.1009167),
                                     ('decker', None),
                                     ('detector_name', None),
                                     ('detector_roi_setting', 'Fixed'),
                                     ('detector_rois_requested', None),
                                     ('detector_section',
                                      [Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=803, x2=1123, y1=565, y2=885),
                                       Section(x1=0, x2=3072, y1=0, y2=3080),
                                       Section(x1=3072, x2=6144, y1=0, y2=3080),
                                       Section(x1=0, x2=3072, y1=3080, y2=6160),
                                       Section(x1=3072, x2=6144, y1=3080,
                                               y2=6160),
                                       Section(x1=0, x2=2048, y1=0, y2=2056),
                                       Section(x1=2048, x2=4096, y1=0, y2=2056),
                                       Section(x1=0, x2=2048, y1=2056, y2=4112),
                                       Section(x1=2048, x2=4096, y1=2056,
                                               y2=4112)]),
                                     ('detector_x_bin', None),
                                     ('detector_x_offset', None),
                                     ('detector_y_bin', None),
                                     ('detector_y_offset', None),
                                     ('disperser', None),
                                     ('dispersion', None),
                                     ('dispersion_axis', None),
                                     ('effective_wavelength', None),
                                     ('elevation', 11.69907514523662),
                                     ('exposure_time', None),
                                     ('filter_name', None),
                                     ('focal_plane_mask', None),
                                     ('gain',
                                      [1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0,
                                       1.0]),
                                     ('gain_setting', None),
                                     ('gcal_lamp', None),
                                     ('group_id', 'None_1_None_None_None'),
                                     ('instrument', 'GHOST'),
                                     ('is_ao', False),
                                     ('is_coadds_summed', True),
                                     ('local_time', datetime.time(10, 0)),
                                     ('lyot_stop', None),
                                     ('mdf_row_id', None),
                                     ('nominal_atmospheric_extinction', 0.0),
                                     ('nominal_photometric_zeropoint',
                                      [None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None]),
                                     ('non_linear_level',
                                      [None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None]),
                                     ('object', 'Dark'),
                                     ('observation_class', 'dayCal'),
                                     ('observation_epoch', None),
                                     ('observation_id', 'GS-2016B-Q-20-5'),
                                     ('observation_type', 'DARK'),
                                     ('overscan_section',
                                      [None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       Section(x1=3072, x2=3104, y1=0, y2=3080),
                                       Section(x1=3072, x2=3104, y1=0, y2=3080),
                                       Section(x1=3072, x2=3104, y1=0, y2=3080),
                                       Section(x1=3072, x2=3104, y1=0, y2=3080),
                                       Section(x1=2048, x2=2080, y1=0, y2=2056),
                                       Section(x1=2048, x2=2080, y1=0, y2=2056),
                                       Section(x1=2048, x2=2080, y1=0, y2=2056),
                                       Section(x1=2048, x2=2080, y1=0, y2=2056)]),
                                     ('pixel_scale', None),
                                     ('program_id', 'GS-2016B-Q-20'),
                                     ('pupil_mask', None),
                                     ('qa_state', 'Pass'),
                                     ('ra', 149.24425),
                                     ('raw_bg', None),
                                     ('raw_cc', None),
                                     ('raw_iq', None),
                                     ('raw_wv', None),
                                     ('read_mode', None),
                                     ('read_noise',
                                      [8.0,
                                       8.0,
                                       8.0,
                                       8.0,
                                       8.0,
                                       8.0,
                                       8.0,
                                       8.0,
                                       8.0,
                                       8.0,
                                       3.0,
                                       3.0,
                                       3.0,
                                       3.0,
                                       3.0,
                                       3.0,
                                       3.0,
                                       3.0]),
                                     ('read_speed_setting', None),
                                     ('requested_bg', None),
                                     ('requested_cc', None),
                                     ('requested_iq', None),
                                     ('requested_wv', None),
                                     ('res_mode', None),
                                     ('saturation_level',
                                      [None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None,
                                       None]),
                                     ('slit', None),
                                     ('target_dec', -69.1009167),
                                     ('target_ra', 149.24425),
                                     ('telescope', 'Gemini-South'),
                                     ('telescope_x_offset', None),
                                     ('telescope_y_offset', None),
                                     ('ut_date', datetime.date(2017, 12, 1)),
                                     ('ut_datetime',
                                      datetime.datetime(2017, 12, 1, 23, 0)),
                                     ('ut_time', datetime.time(23, 0)),
                                     ('want_before_arc', None),
                                     ('wavefront_sensor', None),
                                     ('wavelength_band', None),
                                     ('wcs_dec', None),
                                     ('wcs_ra', None),
                                     ('well_depth_setting', None)),
}
"""Expected descriptors from test files."""
