fixture_data = {
    # Example
    # ('GHOST', 'filename.fits'): ['tag', 'set', 'in', 'full', ],

    # GHOST BIAS
    ('GHOST', 'bias_1_MEF.fits'): ['BIAS',
                                   'BUNDLE',
                                   'CAL',
                                   'GEMINI',
                                   'GHOST',
                                   'NxN',
                                   'RAW',
                                   'SOUTH',
                                   'STD',
                                   'UNPREPARED'],
    ('GHOST', 'bias_1_MEF_1x1_red1.fits'): ['1x1',
                                            'BIAS',
                                            'CAL',
                                            'GEMINI',
                                            'GHOST',
                                            'RAW',
                                            'RED',
                                            'SOUTH',
                                            'SPECT',
                                            'STD',
                                            'UNPREPARED'],

    # GHOST DARK
    ('GHOST', 'dark95_2_MEF.fits'): ['BUNDLE',
                                     'CAL',
                                     'DARK',
                                     'GEMINI',
                                     'GHOST',
                                     'NxN',
                                     'RAW',
                                     'SOUTH',
                                     'STD',
                                     'UNPREPARED'],
    ('GHOST', 'dark95_3_MEF_1x1_blue1.fits'): ['1x1',
                                               'BLUE',
                                               'CAL',
                                               'DARK',
                                               'GEMINI',
                                               'GHOST',
                                               'RAW',
                                               'SOUTH',
                                               'SPECT',
                                               'STD',
                                               'UNPREPARED'],

    # GHOST ARC
    ('GHOST', 'arcAfter95_high_MEF.fits'): ['ARC',
                                            'BUNDLE',
                                            'CAL',
                                            'GEMINI',
                                            'GHOST',
                                            'HIGH',
                                            'NxN',
                                            'PARTNER_CAL',
                                            'RAW',
                                            'SOUTH',
                                            'UNPREPARED'],
    ('GHOST', 'arcBefore95_high_MEF_1x1_red1.fits'): ['1x1',
                                                      'ARC',
                                                      'CAL',
                                                      'GEMINI',
                                                      'GHOST',
                                                      'HIGH',
                                                      'PARTNER_CAL',
                                                      'RAW',
                                                      'RED',
                                                      'SOUTH',
                                                      'SPECT',
                                                      'UNPREPARED'],

    # GHOST FLAT
    ('GHOST', 'flat95_std_1_MEF.fits'): ['BUNDLE',
                                         'CAL',
                                         'FLAT',
                                         'GEMINI',
                                         'GHOST',
                                         'NxN',
                                         'PARTNER_CAL',
                                         'RAW',
                                         'SOUTH',
                                         'STD',
                                         'UNPREPARED'],
    ('GHOST', 'flat95_high_2_MEF_1x1_red1.fits'): ['1x1',
                                                   'CAL',
                                                   'FLAT',
                                                   'GEMINI',
                                                   'GHOST',
                                                   'HIGH',
                                                   'PARTNER_CAL',
                                                   'RAW',
                                                   'RED',
                                                   'SOUTH',
                                                   'SPECT',
                                                   'UNPREPARED'],

    # GHOST SKY
    ('GHOST', 'sky95_high_MEF.fits'): ['BUNDLE',
                                       'GEMINI',
                                       'GHOST',
                                       'HIGH',
                                       'NxN',
                                       'RAW',
                                       'SKY',
                                       'SOUTH',
                                       'UNPREPARED'],
    ('GHOST', 'sky95_std_MEF_1x1_blue1.fits'): ['1x1',
                                                'BLUE',
                                                'GEMINI',
                                                'GHOST',
                                                'RAW',
                                                'SKY',
                                                'SOUTH',
                                                'SPECT',
                                                'STD',
                                                'UNPREPARED'],

    # GHOST OBJECT
    ('GHOST', 'obj95_0.5_high_MEF.fits'): ['BUNDLE', 'GEMINI', 'GHOST', 'HIGH',
                                           'NxN', 'RAW', 'SOUTH', 'UNPREPARED'],
    ('GHOST', 'obj95_0.5_high_MEF_1x1_red1.fits'): ['1x1',
                                                    'GEMINI',
                                                    'GHOST',
                                                    'HIGH',
                                                    'RAW',
                                                    'RED',
                                                    'SOUTH',
                                                    'SPECT',
                                                    'UNPREPARED'],
    ('GHOST', 'obj95_1.0_std_MEF_1x1_blue1.fits'): ['1x1',
                                                    'BLUE',
                                                    'GEMINI',
                                                    'GHOST',
                                                    'RAW',
                                                    'SOUTH',
                                                    'SPECT',
                                                    'STD',
                                                    'UNPREPARED'],

    # GHOST SLIT
    ('GHOST', 'bias_2_MEF_2x2_slit.fits'): ['2x2',
                                            'BIAS',
                                            'CAL',
                                            'GEMINI',
                                            'GHOST',
                                            'IMAGE',
                                            'RAW',
                                            'SLITV',
                                            'SOUTH',
                                            'STD',
                                            'UNPREPARED'],
    ('GHOST', 'dark95_3_MEF_2x2_slit.fits'): ['2x2',
                                              'CAL',
                                              'DARK',
                                              'GEMINI',
                                              'GHOST',
                                              'IMAGE',
                                              'RAW',
                                              'SLITV',
                                              'SOUTH',
                                              'STD',
                                              'UNPREPARED'],
    ('GHOST', 'arcBefore95_high_MEF_2x2_slit.fits'): ['2x2',
                                                      'ARC',
                                                      'CAL',
                                                      'GEMINI',
                                                      'GHOST',
                                                      'HIGH',
                                                      'IMAGE',
                                                      'PARTNER_CAL',
                                                      'RAW',
                                                      'SLITV',
                                                      'SOUTH',
                                                      'UNPREPARED'],
    ('GHOST', 'flat95_std_2_MEF_2x2_slit.fits'): ['2x2',
                                                  'CAL',
                                                  'FLAT',
                                                  'GEMINI',
                                                  'GHOST',
                                                  'IMAGE',
                                                  'PARTNER_CAL',
                                                  'RAW',
                                                  'SLITV',
                                                  'SOUTH',
                                                  'STD',
                                                  'UNPREPARED'],
    ('GHOST', 'obj95_1.0_high_MEF_2x2_slit.fits'): ['2x2',
                                                    'GEMINI',
                                                    'GHOST',
                                                    'HIGH',
                                                    'IMAGE',
                                                    'RAW',
                                                    'SLITV',
                                                    'SOUTH',
                                                    'UNPREPARED'],
    ('GHOST', 'sky95_std_MEF_2x2_slit.fits'): ['2x2',
                                               'GEMINI',
                                               'GHOST',
                                               'IMAGE',
                                               'RAW',
                                               'SKY',
                                               'SLITV',
                                               'SOUTH',
                                               'STD',
                                               'UNPREPARED'],

}
